@Trial.Server_HostAddress = https://localhost:7117


GET {{Trial.Server_HostAddress}}/coa

###

POST {{Trial.Server_HostAddress}}/coa
Content-Type: application/json

{
    "name": "tax",
    "code": "1/2"
}
###

GET {{Trial.Server_HostAddress}}/coa/6aa29657d41f8c5c0d2eff14

###

GET {{Trial.Server_HostAddress}}/tb

###
POST {{Trial.Server_HostAddress}}/tb
Content-Type: application/json

{
  "entries": [
    {
      "accountCode": "1/1",
      "name": "sales",
      "debit": 100.00,
      "credit": 0.00
    },
    {
      "accountCode": "1/2",
      "name": "cash",
      "debit": 0.00,
      "credit": 100.00
    }
  ]
}

###

GET {{Trial.Server_HostAddress}}/tb/6aa298e570137ace0c4a0048

###
